# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CardSelector' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CardSelector

  #Facebook SDK to enable login
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  #The Google Sign-In SDK allows users to sign in with their Google account from third-party apps.
  pod 'Google/SignIn'

  #ObjectMapper is a framework written in Swift that makes it easy
   #for you to convert your model objects (classes and structs) to and from JSON.
   pod 'ObjectMapper', '~> 1.2'

   #Alamofire is an HTTP networking library written in Swift.
   pod 'Alamofire', '~> 3.3'

   #AlamofireImage is an image component library for Alamofire.
   pod 'AlamofireImage', '~> 2.0'

   #Realm is a mobile database that runs directly inside phones, tablets or wearables.
   pod 'RealmSwift', '~> 0.98'
   
   #An easy to use UIAlertController builder for swift
   pod 'LKAlertController', '~> 1.7'

end
